#! /bin/sh

$LSB_TRAPSIGS
$LSB_RCP1
$LSB_RCP2
$LSB_RCP3
# LSBATCH: User input
/usr/local/lsf/etc/job_starter '/afs/cern.ch/work/m/mojoe137/private/CMSSW_4_4_5_patch5/src/Producers/StarLightProducer/scripts/starLit4ppRECOcern.sh '$LSB_JOBINDEX' JPsi MuMu Xn0n Co'
ExitStat=$?
wait
# LSBATCH: End user input
true
exit `expr $? "|" $ExitStat`
